### ISSUE TITLE
Error while building Lava v0.4.0

### ISSUE THREAD

**Issue by Galadrin** [lavanet/lava#226]
## Expected Behavior
build success

## Current Behavior
Error with following log :
```
make install
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=lava -X github.com/cosmos/cosmos-sdk/version.AppName=lavad -X github.com/cosmos/cosmos-sdk/version.Version=0.4.0 -X github.com/cosmos/cosmos-sdk/version.Commit=e2c69db54ed355cb42b02a9fd21faf890f66eca8 -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger, -X github.com/lavanet/lava/relayer/chainproxy.ReturnMaskedErrors=false -X github.com/lavanet/lava/utils.TimeoutMutex=false -w -s' -trimpath  ./...
# github.com/lavanet/lava/cmd/lavad
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF
  -E entry
    	set entry symbol name
  -H type
    	set header type
  -I linker
    	use linker as ELF dynamic linker
  -L directory
    	add specified directory to library path
  -R quantum
    	set address rounding quantum (default -1)
  -T address
    	set text segment address (default -1)
  -V	print version and exit
  -X definition
    	add string value definition of the form importpath.name=value
  -a	no-op (deprecated)
  -asan
    	enable ASan interface
  -aslr
    	enable ASLR for buildmode=c-shared on windows (default true)
  -benchmark string
    	set to 'mem' or 'cpu' to enable phase benchmarking
  -benchmarkprofile base
    	emit phase profiles to base_phase.{cpu,mem}prof
  -buildid id
    	record id as Go toolchain build id
  -buildmode mode
    	set build mode
  -c	dump call graph
  -compressdwarf
    	compress DWARF if possible (default true)
  -cpuprofile file
    	write cpu profile to file
  -d	disable dynamic executable
  -debugnosplit
    	dump nosplit call graph
  -debugtextsize int
    	debug text section max size
  -debugtramp int
    	debug trampolines
  -dumpdep
    	dump symbol dependency graph
  -extar string
    	archive program for buildmode=c-archive
  -extld linker
    	use linker when linking in external mode
  -extldflags flags
    	pass flags to external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -h	halt on error
  -importcfg file
    	read import configuration from file
  -installsuffix suffix
    	set package directory suffix
  -k symbol
    	set field tracking symbol
  -libgcc string
    	compiler support lib for internal linking; use "none" to disable
  -linkmode mode
    	set link mode
  -linkshared
    	link against installed Go shared libraries
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	enable MSan interface
  -n	dump symbol table
  -o file
    	write output to file
  -pluginpath string
    	full path name for plugin
  -r path
    	set the ELF dynamic linker search path to dir1:dir2:...
  -race
    	enable race detector
  -s	disable symbol table
  -strictdups int
    	sanity check duplicate symbol contents during object file reading (1=warn 2=err).
  -tmpdir directory
    	use directory for temporary files
  -v	print link trace
  -w	disable DWARF generation
make: *** [Makefile:95: install] Error 2
```

## Steps to Reproduce
1 - install go v1.19.4
2 - checkout lava v0.4.0
3 - make build or make install

## Environment
OS and version: Debian 11

**Comment by AviaOne** [comment]
Just to confirm because I tested with Go version 1.18.3 and Yes it works !
I have been able to use the standart process to use the binary 👍 

cd $HOME
git clone https://github.com/lavanet/lava.git
cd lava
git checkout  v0.4.0
make install

**It return** 
name: lava
server_name: lavad
version: 0.4.0
commit: e2c69db54ed355cb42b02a9fd21faf890f66eca8
build_tags: netgo,ledger
go: go version go1.18.3 linux/amd64

I strongly recommend to add this point everywhere because most of the docs are using
git clone https://github.com/K433QLtr6RA9ExEq/GHFkqmTzpdNLDd6T.git
wget https://lava-binary-upgrades.s3.amazonaws.com/testnet/v0.3.0/lavad

This is can create security fail to recommand in the official doc to get the binary from s3.amazonaws.com
Get the binary directly from https://github.com/lavanet/lava.git is much more safe 👍

**Comment by AviaOne** [comment]
> we currently work with go1.18 please try to downgrade the go version and try again.
.
